### ISSUE TITLE
حرف (ج)

### ISSUE THREAD

**Issue by alim0820** [shahabbai/Persian_Plate_Recognition#2]
سلام.
داشتم برنامه رو تست میکردم، متوجه شدم که حرف "ج" رو نمی تونه تشخیص بده.
البته اشتباه تشخیص میده (معلول تشخیص)
و همینطور حرف "ک" که "ب" تشخیص میده

فعلا همین ها رو متوجه شدم.

**Comment by shahabbai** [comment]
Thanks for your issue @sAlim0820  . Please keep the language in English. Send me your data which you tested with char "ج". In my dataset there is no char with "ک", because this char on plates is rare and I didn't have any data of it, And for "ج" result, this is one of my test data and the result is correct.
![image](https://github.com/shahabbai/PersianPlateRecog/assets/133869713/231fd46e-54e7-49d6-b13c-16576387df90)
