### ISSUE TITLE
Train custom model

### ISSUE THREAD

**Issue by omidmousavi** [shahabbai/Persian_Plate_Recognition#3]
Hello,
First of all, thank you for this good repository.

---

I found a better dataset for plate numbers detection in roboflow [(persian-plates-number)](https://universe.roboflow.com/azsdf/persian-plates-number) It can even improve...
Anyway...
I want to know how can i train custom model with YOLO...
My laptop is not appropriate for training and google colab stop training after a few hours, also i can not download trained file from roboflow :(

Do you know any other solution?

Thanks for your attention. ❤️🙏

**Comment by shahabbai** [comment]
Hello there, Thank you for the issue.
Thanks for sharing this dataset. It's more general compare to my dataset, but this dataset contains motorcycles's licence plate too. My main model can't detect motorcycles's licence plate because my dataset is just contains cars. But it's ok you can just train your main model with bunch of motorcycles's licence plate to detect it. What model did you choose for training? For big models of course it took more time and my suggest is only use small and nano model. 
If you want to use google colab you can just use some script out there to do left click on your colab webpage. You can also use Amazon Sagemaker for training. It's like colab and you can use GPU for 6 hours in a day and it's free.

**Comment by omidmousavi** [comment]
Okay. Right...
Can i ask, how did you train your dataset? with colab? personal system ? or something else ?
Or if you want to train this dataset use what? / which is the best option for training a dataset like it?

Thank you very much. 🙏

**Comment by shahabbai** [comment]
My dataset contains 1485 images and I trained it with nano model via google colab. It didn't took alot of time because my dataset is not that big. But for this dataset which you shared, It contains 6222 images. For train this dataset if you have not a good local PC so for you, best options is just google colab or maybe kaggle or the other free websites, or maybe you can google it about some websites in iran that they rent servers with good GPU. You can just rent it for 1 or 2 days and do your training.

**Comment by omidmousavi** [comment]
👌 OK
I have one more question. 😅
How many epochs is good for training a dataset like this?

**Comment by shahabbai** [comment]
Something between 250 to 300 epochs should be enough.

**Comment by omidmousavi** [comment]
Okay, thanks again. it was very helpful...
